apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: staging-

# The namePrefix changes the frontend Service to "staging-activemq-dashboard-frontend"
# and the backend Service to "staging-activemq-dashboard-backend".
# Patch BACKEND_URL in the frontend to match the prefixed backend Service name.
patches:
  - target:
      kind: Deployment
      name: activemq-dashboard-frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "http://staging-activemq-dashboard-backend:8080"
